version: '3.8'

services:
    web:
        build: .
        container_name: mein_php_server
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html/
        # Dieser Befehl ändert das Hauptverzeichnis auf /public und aktiviert mod_rewrite
        command: >
            bash -c "sed -i 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/000-default.conf
            && a2enmod rewrite
            && apache2-foreground"
    db:
        image: mysql:8.0
        container_name: meine_datenbank
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: seelenfunke  # Hier den Namen deiner DB eintragen
        ports:
            - "3306:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
        depends_on:
            - db
