#!/bin/bash

case "$1" in
    start)
        echo "🚀 Starte Funki..."
        docker compose up -d
        ;;
    stop)
        echo "🛑 Stoppe Funki..."
        docker compose down
        ;;
    bauen)
        echo "🏗️ Baue Funki neu..."
        docker compose up -d --build
        ;;
    löschen)
        echo "💥 Lösche Funki (inkl. Volumes)..."
        docker compose down -v
        ;;
    migrate)
        echo "🗄️ Führe Migrationen und Seeder aus..."
        docker compose exec web php artisan migrate:fresh --seed
        ;;
    key)
        echo "🗄️ Führe Key Generate aus..."
        docker compose exec web php artisan key:generate
        ;;
    storage)
        echo "🗂️ Lösche alten Storage-Link restlos..."
        docker compose exec web rm -rf public/storage
        echo "🔗 Erstelle neuen Storage-Link..."
        docker compose exec web php artisan storage:link
        echo "✅ Storage-Link erfolgreich erneuert!"
        ;;
    export)
        echo "🗄️ Exportiere Projektdateien..."
        docker compose exec web php artisan project:export
        ;;
    artisan)
        shift
        # Zwingt Docker, deine lokale Ubuntu-ID anstelle von 'root' zu nutzen
        docker compose exec --user "$(id -u):$(id -g)" web php artisan "$@"
        ;;


    *)
        echo "💥 Funki ist bereit! Nutze: funki start, stop, bauen, löschen oder migrate"
        exit 1
        ;;
esac
