<!DOCTYPE html>
<html lang="de">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title ?? 'Bericht' }}</title>
    <style>
        @page { size: A4 portrait; margin: 15mm 15mm 20mm 15mm; }
        body { font-family: sans-serif; font-size: 11px; color: #333333; margin: 0; padding: 0; line-height: 1.5; background-color: #ffffff; }

        /* Typography */
        h1, h2, h3, h4 { color: #000000; margin-top: 20px; margin-bottom: 10px; }
        h1 { font-size: 18px; border-bottom: 1px solid #cccccc; padding-bottom: 5px; }
        h2 { font-size: 15px; border-bottom: 1px solid #eeeeee; padding-bottom: 4px; }
        h3 { font-size: 13px; }
        p { margin-bottom: 10px; }
        
        /* Layout */
        .header { margin-bottom: 30px; padding-bottom: 10px; border-bottom: 1px solid #cccccc; }
        .doc-title { font-size: 22px; font-weight: bold; color: #000000; margin: 0 0 5px 0; }
        .doc-meta { font-size: 9px; color: #666666; margin-top: 10px; }

        /* Tables generated by Markdown */
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; margin-top: 10px; page-break-inside: avoid; }
        th, td { border: 1px solid #dddddd; padding: 6px 8px; text-align: left; font-size: 10px; }
        th { background-color: #f9f9f9; font-weight: bold; color: #333333; }
        
        /* Elements */
        ul, ol { margin-bottom: 15px; padding-left: 20px; }
        li { margin-bottom: 5px; }
        strong { color: #000000; }
        hr { border: 0; border-top: 1px solid #eeeeee; margin: 20px 0; }
        pre, code { background-color: #f9f9f9; padding: 2px 4px; border-radius: 3px; font-family: monospace; font-size: 10px; }
        pre { padding: 10px; overflow-x: auto; border: 1px solid #dddddd; }

        .page-break { page-break-after: always; }
        .clearfix { clear: both; }
        
        #footer { position: fixed; bottom: -15mm; left: 0px; right: 0px; height: 10mm; font-size: 8px; color: #666666; border-top: 1px solid #cccccc; padding-top: 4px; }
        .footer-table { width: 100%; border-collapse: collapse; border: none; }
        .footer-table td { border: none; padding: 0; background: transparent; }
        .page-number:after { content: "Seite " counter(page); font-weight: bold; }
    </style>
</head>
<body>

<div id="footer">
    <table class="footer-table">
        <tr>
            <td style="text-align: left; width: 33%;">Bericht</td>
            <td style="text-align: center; width: 33%; color: #000000;" class="page-number"></td>
            <td style="text-align: right; width: 33%;">Erstellt am: {{ date('d.m.Y') }}</td>
        </tr>
    </table>
</div>

<div class="header">
    <div class="doc-title">{{ $title ?? 'Bericht' }}</div>
    <div class="doc-meta">
        Erstellt am: {{ date('d.m.Y, H:i') }} Uhr
    </div>
</div>

<div class="content">
    {!! $htmlContent ?? '' !!}
</div>

</body>
</html>
