<!DOCTYPE html>
<html lang="de">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>{{ $title ?? 'Bericht' }} - Mein Seelenfunke</title>
    <style>
        @page { size: A4 portrait; margin: 15mm 15mm 20mm 15mm; }
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; font-size: 11px; color: #2d3748; margin: 0; padding: 0; line-height: 1.5; background-color: #ffffff; }

        /* Typography */
        h1, h2, h3, h4 { color: #111827; margin-top: 20px; margin-bottom: 10px; }
        h1 { font-size: 18px; border-bottom: 2px solid #C5A059; padding-bottom: 5px; text-transform: uppercase; }
        h2 { font-size: 15px; color: #C5A059; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
        h3 { font-size: 13px; }
        p { margin-bottom: 10px; }
        
        /* Layout */
        .header { margin-bottom: 30px; padding-bottom: 10px; border-bottom: 1px solid #e5e7eb; position: relative; }
        .logo { height: 60px; position: absolute; right: 0; top: 0; }
        .doc-title { font-size: 22px; font-weight: 900; color: #111827; margin: 0 0 5px 0; text-transform: uppercase; letter-spacing: 1px; }
        .erp-tag {
            display: inline-block; background: linear-gradient(135deg, #d4af37, #f3e5ab, #d4af37);
            color: #111827; padding: 3px 8px; font-size: 9px; font-weight: bold;
            border-radius: 3px; text-transform: uppercase; margin-bottom: 5px; border: 1px solid #b38b42;
        }
        .doc-meta { font-size: 9px; color: #6b7280; margin-top: 10px; }

        /* Tables generated by Markdown */
        table { width: 100%; border-collapse: collapse; margin-bottom: 15px; margin-top: 10px; page-break-inside: avoid; }
        th, td { border: 1px solid #e5e7eb; padding: 6px 8px; text-align: left; font-size: 10px; }
        th { background-color: #f3f4f6; font-weight: bold; color: #374151; }
        
        /* Elements */
        ul, ol { margin-bottom: 15px; padding-left: 20px; }
        li { margin-bottom: 5px; }
        strong { color: #111827; }
        hr { border: 0; border-top: 1px solid #e5e7eb; margin: 20px 0; }
        pre, code { background-color: #f3f4f6; padding: 2px 4px; border-radius: 3px; font-family: monospace; font-size: 10px; }
        pre { padding: 10px; overflow-x: auto; }

        .page-break { page-break-after: always; }
        .clearfix { clear: both; }
        
        #footer { position: fixed; bottom: -15mm; left: 0px; right: 0px; height: 10mm; font-size: 8px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 4px; }
        .footer-table { width: 100%; border-collapse: collapse; border: none; }
        .footer-table td { border: none; padding: 0; background: transparent; }
        .page-number:after { content: "Seite " counter(page); font-weight: bold; }
    </style>
</head>
<body>

<div id="footer">
    <table class="footer-table">
        <tr>
            <td style="text-align: left; width: 33%;"><strong>{{ shop_setting('owner_name', 'Mein Seelenfunke') }}</strong> | {{ $title ?? 'KI-Bericht' }}</td>
            <td style="text-align: center; width: 33%; color: #111827;" class="page-number"></td>
            <td style="text-align: right; width: 33%;">Generiert von KI Agent: {{ $agentName ?? 'System' }}</td>
        </tr>
    </table>
</div>

<div class="header">
    <img src="{{ public_path('shop/projekt/logo/mein-seelenfunke-logo.svg') }}" alt="Logo" class="logo">
    <div class="doc-title">{{ $title ?? 'Bericht' }}</div>
    <div class="erp-tag">Automatisierter KI-Bericht</div>
    <div class="doc-meta">
        Erstellt am: {{ date('d.m.Y, H:i') }} Uhr<br>
    </div>
</div>

<div class="content">
    {!! $htmlContent ?? '' !!}
</div>

</body>
</html>
