                    <!-- Navigation Tabs -->
                    <div x-show="!isChatFullScreen" class="bg-gray-900/80 backdrop-blur-xl border border-gray-800 rounded-xl px-6 flex justify-center gap-8 text-sm tracking-wider font-mono shrink-0 shadow-lg relative overflow-hidden">
                        <div class="absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-[var(--theme-color-50)] to-transparent"></div>
                        <button @click="activeTab = 'workspace'" class="py-3 px-2 relative transition-colors border-b-2" :class="activeTab === 'workspace' ? 'text-[var(--theme-color)] border-[var(--theme-color)] shadow-[0_4px_15px_-3px_var(--theme-color-30)] font-bold' : 'text-gray-400 border-transparent hover:text-gray-200'"><x-heroicon-o-squares-2x2 class="w-4 h-4 inline-block -mt-0.5 mr-1"/> Workspace</button>
                        <button @click="activeTab = 'chat'" class="py-3 px-2 relative transition-colors border-b-2" :class="activeTab === 'chat' ? 'text-[var(--theme-color)] border-[var(--theme-color)] shadow-[0_4px_15px_-3px_var(--theme-color-30)] font-bold' : 'text-gray-400 border-transparent hover:text-gray-200'"><x-heroicon-o-chat-bubble-left-right class="w-4 h-4 inline-block -mt-0.5 mr-1"/> Chat</button>

                        <button @click="activeTab = 'files'" class="py-3 px-2 relative transition-colors border-b-2" :class="activeTab === 'files' ? 'text-[var(--theme-color)] border-[var(--theme-color)] shadow-[0_4px_15px_-3px_var(--theme-color-30)] font-bold' : 'text-gray-400 border-transparent hover:text-gray-200'"><x-heroicon-o-folder-open class="w-4 h-4 inline-block -mt-0.5 mr-1"/> Dateien @if(count($this->fileManagerItems) > 0)<span class="ml-1 bg-[var(--theme-color)] text-black text-[10px] font-bold px-1.5 py-0.5 rounded-full shadow-lg">{{ count($this->fileManagerItems) }}</span>@endif</button>
                        <button @click="activeTab = 'health'" class="py-3 px-2 relative transition-colors border-b-2 text-[var(--theme-color)]" :class="activeTab === 'health' ? 'border-[var(--theme-color)] shadow-[0_4px_15px_-3px_var(--theme-color-30)] font-bold' : 'border-transparent opacity-80 hover:opacity-100'"><x-heroicon-o-heart class="w-4 h-4 inline-block -mt-0.5 mr-1"/> Gesundheit</button>
                    </div>
