<?php

namespace App\Jobs;

use App\Models\Ai\AiWorkspaceTask;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\Log;

class ProcessAiWorkspaceTask implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public $timeout = 600; // 10 Minutes max LLM inference
    public $tries = 2; // Allow one retry before permanent fail

    public function __construct(
        public AiWorkspaceTask $task
    ) {}

    public function handle(): void
    {
        #Log::info("Processing AI Workspace Task: {$this->task->id}");

        $this->task->update(['status' => 'processing']);
        \App\Events\TaskUpdated::dispatch($this->task);

        $agent = $this->task->agent;
        if (!$agent) {
             Log::error("No agent assigned to Workspace Task: {$this->task->id}");
             $this->task->update(['status' => 'failed', 'response_content' => 'Error: No agent assigned.']);
             \App\Events\TaskUpdated::dispatch($this->task);
             return;
        }

        try {
            $metadata = $this->task->ui_metadata ?? [];
            $plan = $metadata['execution_plan'] ?? [];
            $history = $metadata['llm_history'] ?? [];

            $apiService = \App\Services\AI\AiAgentFactory::make($agent);

            // Inject the user's web session ID into the job process context
            // so artifacts generated by the background agent correctly link to the UI.
            if (!empty($metadata['session_id'])) {
                config(['ai.current_session_id' => $metadata['session_id']]);
            }

            // -------------------------------------------------------------
            // PHASE 1: DRAFTING THE PLAN
            // -------------------------------------------------------------
            if (empty($plan)) {
                $contentArray = [];
                $contentArray[] = ['type' => 'text', 'text' => "SWARM ORCHESTRATOR INSTRUCTION:\nDu bist im PLANUNGSMODUS. Bevor du die eigentliche Aufgabe startest, musst du die Aufgabe zwingend in Einzelschritte zerlegen.\nDeine Ausgabe darf AUSSCHLIESSLICH ein valides JSON-Array sein, nichts anderes! Formatiere es als: [{\"id\": 1, \"description\": \"...\"}, {\"id\": 2, \"description\": \"...\"}]. VERWENDE KEINE WERKZEUGE JETZT!\n\nBEACHTE: Du hast bereits vollen Zugriff auf die angehängten Dateien (siehe [FILE ATTACHMENT] oder [UPLOADED FILE] weiter unten). Du MUSST NICHT mehr nach diesen Dateien suchen oder sie einlesen. Dein Plan kann direkt mit der Verarbeitung/Modifikation dieser Dateien beginnen!\n\nAUFGABE: " . $this->task->prompt];

                // Append Attachments for Context during planning
                if (!empty($metadata['attachments'])) {
                    foreach ($metadata['attachments'] as $fPath) {
                        try {
                            $fileStr = file_get_contents($fPath);
                            $ext = strtolower(pathinfo($fPath, PATHINFO_EXTENSION));
                            if (in_array($ext, ['png','jpg','jpeg','webp','gif'])) {
                                $b64 = base64_encode($fileStr);
                                $mime = 'image/' . ($ext === 'jpg' ? 'jpeg' : $ext);
                                $contentArray[] = ['type' => 'image_url', 'image_url' => ['url' => "data:{$mime};base64,{$b64}"]];
                            } else {
                                $contentArray[] = ['type' => 'text', 'text' => "\n\n--- [FILE ATTACHMENT: ".basename($fPath)."] ---\n" . $fileStr . "\n--- [END OF FILE] ---\n\n"];
                            }
                        } catch (\Exception $e) {}
                    }
                }

                if (!empty($metadata['local_uploads'])) {
                    foreach ($metadata['local_uploads'] as $upl) {
                        try {
                            $fPath = storage_path('app/public/' . $upl['path']);
                            $fileStr = file_get_contents($fPath);
                            $ext = strtolower(pathinfo($fPath, PATHINFO_EXTENSION));
                            if (in_array($ext, ['png','jpg','jpeg','webp','gif'])) {
                                $b64 = base64_encode($fileStr);
                                $mime = 'image/' . ($ext === 'jpg' ? 'jpeg' : $ext);
                                $contentArray[] = ['type' => 'image_url', 'image_url' => ['url' => "data:{$mime};base64,{$b64}"]];
                            } else {
                                $contentArray[] = ['type' => 'text', 'text' => "\n\n--- [UPLOADED FILE: ".basename($upl['name'])."] ---\n" . $fileStr . "\n--- [END OF FILE] ---\n\n"];
                            }
                        } catch (\Exception $e) {}
                    }
                }

                $messages = [['role' => 'user', 'content' => $contentArray]];

                // Force LLM to plan without tools using a mocked empty toolset
                $agentClone = clone $agent;
                $agentClone->tools = collect([]);
                $planningApiService = \App\Services\AI\AiAgentFactory::make($agentClone);

                $responseArray = $planningApiService->ask($messages);
                $response = $responseArray['response'] ?? '[]';

                // Robust JSON Cleanup
                $jsonStr = preg_replace('/```json/i', '', $response);
                $jsonStr = preg_replace('/```/i', '', $jsonStr);
                $jsonStr = trim($jsonStr);

                $parsedPlan = json_decode($jsonStr, true);
                if (is_array($parsedPlan)) {
                    foreach ($parsedPlan as $idx => $step) {
                        $plan[] = [
                            'id' => $step['id'] ?? ($idx + 1),
                            'description' => $step['description'] ?? 'Unbekannter Schritt',
                            'status' => 'pending',
                            'result' => null
                        ];
                    }
                } else {
                    // Fallback if AI fails JSON parsing
                    $plan[] = [
                        'id' => 1,
                        'description' => 'Führe die Aufgabe aus: ' . substr($this->task->prompt, 0, 100) . '...',
                        'status' => 'pending',
                        'result' => null
                    ];
                }

                $history = $responseArray['history'] ?? $messages; // start history trace

                $metadata['execution_plan'] = $plan;
                $metadata['llm_history'] = $history;
                $this->task->update(['ui_metadata' => $metadata]);
                \App\Events\TaskUpdated::dispatch($this->task);

                $settings = \App\Models\Ai\AiUserWorkspaceSetting::first();
                $autoApprove = $settings->auto_approve_execution_plan ?? false;
                if (!$autoApprove) {
                    $this->task->update(['status' => 'awaiting_approval']);
                    \App\Events\TaskUpdated::dispatch($this->task);
                    return; // Pause the queue job
                }
            }

            // -------------------------------------------------------------
            // PHASE 2: EXECUTION LOOP
            // -------------------------------------------------------------
            $allCompleted = true;
            $finalSummaryNeeded = empty($this->task->response_content);

            foreach ($plan as $index => &$step) {
                if ($step['status'] === 'completed' || $step['status'] === 'failed') {
                    continue;
                }

                $allCompleted = false;

                // Mark current step as processing
                $step['status'] = 'processing';
                $metadata['execution_plan'] = $plan;
                $this->task->update(['ui_metadata' => $metadata]);
                \App\Events\TaskUpdated::dispatch($this->task);

                // Ask AI to execute this step exclusively
                $history[] = [
                    'role' => 'user',
                    'content' => "Führe nun folgenden Schritt aus (und nutze falls nötig deine Werkzeuge dafür): \nSchritt " . $step['id'] . ": " . $step['description'] . "\nGib eine kurze Bestätigung oder das Ergebnis des Schritts zurück, wenn du fertig bist."
                ];

                if (!isset($metadata['work_log'])) {
                    $metadata['work_log'] = [];
                }
                $metadata['work_log'][] = ['time' => now()->format('H:i:s'), 'type' => 'info', 'message' => "Thinking...", 'color' => 'yellow'];
                $this->task->update(['ui_metadata' => $metadata]);
                \App\Events\TaskUpdated::dispatch($this->task);

                $startTime = microtime(true);
                $lastActionTime = microtime(true);

                $streamCallback = function($event) use (&$lastActionTime) {
                    if (($event['type'] ?? '') === 'tool_call') {
                        $toolName = $event['tool'] ?? 'System';
                        $friendlyName = "Nutze Werkzeug " . str_replace('system_', '', $toolName) . "...";
                        $speechText = "Ich nutze ein Werkzeug.";
                        
                        if ($toolName === 'system_write_artifact') {
                            $friendlyName = "Generating...";
                            $speechText = "Ich generiere ein Dokument.";
                        }
                        else if ($toolName === 'system_multi_replace_file' || $toolName === 'system_replace_file' || str_contains($toolName, 'edit')) {
                            $friendlyName = "Editing...";
                            $speechText = "Ich bearbeite eine Datei.";
                        }
                        else if ($toolName === 'system_run_command' || str_contains($toolName, 'command')) {
                            $friendlyName = "Ran command...";
                            $speechText = "Ich führe einen Befehl aus.";
                        }
                        else if ($toolName === 'system_read_file' || str_contains($toolName, 'view')) {
                            $friendlyName = "Reading...";
                            $speechText = "Ich analysiere den Quellcode.";
                        }
                        else if ($toolName === 'grep_search' || str_contains($toolName, 'search')) {
                            $friendlyName = "Searching...";
                            $speechText = "Ich suche im System.";
                        }
                        else if ($toolName === 'system_list_directory' || str_contains($toolName, 'list')) {
                            $friendlyName = "Listing dir...";
                            $speechText = "Ich analysiere die Ordnerstruktur.";
                        }

                        // Broadcast the event so the active widget can read it out loud
                        if (class_exists(\App\Events\AiWidgetSpeechEvent::class)) {
                            broadcast(new \App\Events\AiWidgetSpeechEvent($this->task->assigned_agent_id ?? 'system', $speechText));
                        }

                        $thinkDuration = round(microtime(true) - $lastActionTime, 1);
                        if ($thinkDuration > 0.5) {
                            $t = $this->task->fresh();
                            $md = $t->ui_metadata ?? [];
                            $md['work_log'][] = ['time' => now()->format('H:i:s'), 'type' => 'success', 'message' => "Thought for {$thinkDuration} seconds.", 'color' => 'emerald'];
                            $t->update(['ui_metadata' => $md]);
                            \App\Events\TaskUpdated::dispatch($t);
                        }

                        $t = $this->task->fresh();
                        $md = $t->ui_metadata ?? [];
                        $md['work_log'][] = ['time' => now()->format('H:i:s'), 'type' => 'tool', 'message' => $friendlyName, 'color' => 'cyan'];
                        $t->update(['ui_metadata' => $md]);
                        \App\Events\TaskUpdated::dispatch($t);

                        $lastActionTime = microtime(true);
                    }
                };

                $stepResponseArray = $apiService->ask($history, $streamCallback);
                $stepResult = $stepResponseArray['response'] ?? 'Keine Antwort.';

                $thinkDuration = round(microtime(true) - $lastActionTime, 1);
                if ($thinkDuration > 0.5) {
                    $t = $this->task->fresh();
                    $md = $t->ui_metadata ?? [];
                    $md['work_log'][] = ['time' => now()->format('H:i:s'), 'type' => 'success', 'message' => "Thought for {$thinkDuration} seconds.", 'color' => 'emerald'];
                    $t->update(['ui_metadata' => $md]);
                    \App\Events\TaskUpdated::dispatch($t);
                }

                if (str_contains(strtoupper($stepResult), '[SKIP]')) {
                    $this->task->update(['status' => 'pending', 'assigned_agent_id' => null]);
                    return;
                }

                $history = $stepResponseArray['history'] ?? $history;

                $step['status'] = 'completed';
                $step['result'] = $stepResult;
                
                // Fetch fresh metadata to avoid overwriting stream logs
                $freshMd = $this->task->fresh()->ui_metadata ?? [];
                $freshMd['execution_plan'] = $plan;
                $freshMd['llm_history'] = $history;
                
                // Replace the 'Thinking...' log with a completion mark
                if (!empty($freshMd['work_log'])) {
                    foreach (array_reverse(array_keys($freshMd['work_log'])) as $k) {
                        if ($freshMd['work_log'][$k]['message'] === 'Thinking...') {
                            $freshMd['work_log'][$k] = [
                                'time' => now()->format('H:i:s'),
                                'type' => 'success',
                                'message' => "Completed step " . $step['id'],
                                'color' => 'gray'
                            ];
                            break;
                        }
                    }
                }

                $this->task->update(['ui_metadata' => $freshMd]);
                \App\Events\TaskUpdated::dispatch($this->task);
            }

            // -------------------------------------------------------------
            // PHASE 3: FINALIZATION
            // -------------------------------------------------------------
            if ($allCompleted && $finalSummaryNeeded) {
                $history[] = [
                    'role' => 'user',
                    'content' => "Alle Schritte sind abgeschlossen. Bitte bestätige den Abschluss der Aufgabe. WICHTIG: Halte dich extrem kurz (max. 1-2 Sätze). Beginne mit 'Verstanden, ich habe...' oder 'Erledigt'. Verzichte vollständig auf technische Details, Erklärungen oder Zusammenfassungen der einzelnen Schritte."
                ];
                $finalRespArray = $apiService->ask($history);
                $finalResponse = $finalRespArray['response'] ?? 'Aufgabe erfolgreich abgeschlossen.';

                $this->task->update([
                    'status' => 'completed',
                    'response_content' => $finalResponse,
                    'completed_at' => now(),
                ]);
            } else {
                // Should only be reached if $allCompleted is false and we loop again, but we just completed all in the foreach.
                // Wait, if foreach completes them all, the loop finishes. It should always hit $allCompleted if it doesn't crash.
                if (count(array_filter($plan, fn($s) => $s['status'] === 'pending')) === 0) {
                     $this->task->update([
                         'status' => 'completed',
                         'response_content' => 'Alle definierten Schritte wurden in der Historie abgeschlossen.',
                         'completed_at' => now(),
                     ]);
                }
            }

        } catch (\Exception $e) {
            $this->task->update(['status' => 'failed', 'response_content' => 'Systemfehler beim Ausführen des Plans: ' . $e->getMessage()]);
        }

        \App\Events\TaskUpdated::dispatch($this->task);
    }
}
